name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache: true

    - name: Sincronizar Módulos
      run: go mod tidy

    - name: Compilar Binário
      run: go build -v ./...
